renaming and updating project template
smartcontractresearchforum/docs pull request #63
Opened 2022-07-25 21:00 UTC by vsterling

renaming project_research_improvement_proposal.md to project_proposal_template.md, edited doc with updated content

2022-08-02 16:56 UTC, ghettodev requested changes

2022-08-02 16:56 UTC, ghettodev commented on en/project_proposal_template.md
> +
Not sure it's a great idea to link to google docs that are anon access and allow editing. Can we get these examples converted to markdown and put into the repo?

2022-08-16 19:33 UTC, vsterling reviewed
The suggestions are resolved -- all Google doc links removed.

2022-10-04 21:07 UTC, SirAh0 commented
close at @marvino3  request, no longer relevant.

2022-10-04 21:07 UTC, closed without merging