Create HowToContributeSCRF_CN
smartcontractresearchforum/docs pull request #7
Opened 2021-05-19 07:49 UTC by Gearlad

2021-05-19 17:00 UTC, ghettodev requested changes

2021-05-19 17:00 UTC, ghettodev commented on cn/HowToContributeSCRF_CN
> +## 我們的研究人員
Should be a line break after every heading as per markdown spec.

2021-05-19 17:00 UTC, ghettodev commented on cn/HowToContributeSCRF_CN
> +* [目前需要的專業](https://www.smartcontractresearch.org/tag/summary)
Let's stick with `-` for list items

2021-05-19 17:00 UTC, ghettodev commented on cn/HowToContributeSCRF_CN
> +如果您因為您的大學或資助機構而不能接受直接付款，我們可以討論替代方案。這可能包括：
This character seems strange as well `：`. Is it also a convention to use that instead of `:` for Chinese translations?

2021-05-19 17:00 UTC, ghettodev commented on cn/HowToContributeSCRF_CN
> +為什麼您對這個論壇感興趣。
Looks like we lost the list items here.

2021-05-19 17:00 UTC, ghettodev commented on cn/HowToContributeSCRF_CN
> +也歡迎您隨時來我們的聊天室介紹自己。
Was there a link to the chat here?

2021-05-19 17:00 UTC, ghettodev commented on cn/HowToContributeSCRF_CN
> +聊天：我們使用Discord [#general chat](https://discord.com/channels/784234332617048065/784234333111451670)來討論內容、區塊鏈相關活動、合作和專案規劃。
these two headings should be bold like the last one please.

2021-05-24 03:30 UTC, 29988122 commented
Suggestion:

It's more formal to use 
```
zh
```
than
```
cn
```
in order to better recognize the different language local accent/variant of the two.

2021-08-20 04:09 UTC, closed without merging